/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: aidan.c.moisan (https://sketchfab.com/aidan.c.moisan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wizard-61156b78c1634dd08b8965d034812a43
Title: Wizard
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three';
export default function Wizard(props) {
    const { nodes, materials } = useGLTF('/models/wizard.glb')

    const modelRef = useRef()

    useFrame((state, delta, xrFrame) => {
        //console.log(state.clock)
        modelRef.current.position.y = -1.05 + Math.sin(state.clock.elapsedTime) * 0.15;
    })

    Object.values(materials).forEach((material) => {
        material.transparent = false;
        material.opacity = 1;
        material.depthTest = true;
        material.depthWrite = true;
        material.side = THREE.DoubleSide;
    });

    return (
        <group {...props} dispose={null}
            ref={modelRef}
            position={[-2.75, -1.5, 0]}
            scale={[1.1, 1.1, 1.1]}
            rotation={[0.25, -0.35, 0]}
        >
            <group position={[2.764, 0, 0]}>
                <primitive object={nodes.GLTF_created_0_rootJoint} />
                <skinnedMesh
                    geometry={nodes.Object_7.geometry}
                    material={materials['Material.001']}
                    skeleton={nodes.Object_7.skeleton}
                />
                <skinnedMesh
                    geometry={nodes.Object_9.geometry}
                    material={materials['Material.001']}
                    skeleton={nodes.Object_9.skeleton}
                />
                <skinnedMesh
                    geometry={nodes.Object_11.geometry}
                    material={materials['Material.001']}
                    skeleton={nodes.Object_11.skeleton}
                />
                <skinnedMesh
                    geometry={nodes.Object_15.geometry}
                    material={materials.Material}
                    skeleton={nodes.Object_15.skeleton}
                />
                <skinnedMesh
                    geometry={nodes.Object_17.geometry}
                    material={materials['Material.006']}
                    skeleton={nodes.Object_17.skeleton}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_13.geometry}
                    material={materials['Material.006']}
                    position={[-0.878, 1.535, 0.167]}
                    rotation={[0.095, 0.189, -0.034]}
                    scale={[0.019, 0.503, 0.019]}
                />
            </group>
        </group>
    )
}

useGLTF.preload('/models/wizard.glb')
